[package]
name = "bash"
version = "5.3"
description = "Bourne-Again Shell"
category = "shells"
license = "GPLv3"
homepage = "https://www.gnu.org/software/bash/"
maintainer = "Zeropkg LFS Automation"
stage = "final"
priority = "normal"

[source]
urls = ["https://ftp.gnu.org/gnu/bash/bash-5.3.tar.gz"]
sha256 = ["PLACEHOLDER_SHA256_BASH_5_3"]
extract_to = "bash-5.3"

[build]
depends = ["ncurses"]  
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "bash-5.3"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
MAKEFLAGS = "-j$(nproc)"
PATH = "/tools/bin:/usr/bin:/bin"
CFLAGS = "-O2 -pipe"
LC_ALL = "POSIX"

[prepare]
commands = [
  "mkdir -v build"  # embora não use build/ no LFS, manter compatibilidade com estrutura
]

[configure]
commands = [
  "pushd .",
  "./configure --prefix=/usr --build=$(support/config.guess) --host=$LFS_TGT --without-bash-malloc",
  "popd"
]

[compile]
commands = ["make"]

[install]
commands = [
  "make DESTDIR=$LFS install",
  "ln -sv bash $LFS/bin/sh"
]

[hooks]
post_install = [
  "echo '[HOOK] Bash 5.3 instalado com sucesso'",
  "ln -sv bash $LFS/bin/sh"
]

[patches]
apply = []
strip = 1

[tests]
enabled = false

[package.files]
bin = ["/usr/bin/bash", "/usr/bin/sh"]
doc = ["/usr/share/doc/bash-5.3"]

[install]
root = "/mnt/lfs"
safe_chroot = true
parallel_install = false
keep_build = false
overwrite_existing = true

[notifications]
notify = true
urgency = "normal"
summary = "Bash 5.3 instalado"
icon = "/usr/share/icons/bash.png"
