# GNU Binutils — Fase Final
# Receita completa para uso com Zeropkg (LFS ou sistema normal)
# ------------------------------------------------------------
# Esta receita constrói e instala os binários definitivos de montagem e linkagem
# após a construção do toolchain (binutils-pass1, gcc-pass1, glibc, etc.)
# ------------------------------------------------------------

[package]
name = "binutils"
version = "2.43.1"
category = "base"
variant = "final"
description = "GNU Binutils — conjunto de ferramentas para montagem e linkagem (fase final)."
maintainer = "Zeropkg Build System"
license = "GPL-3.0"
homepage = "https://www.gnu.org/software/binutils/"

# ------------------------------------------------------------
# Fontes — múltiplos mirrors
# ------------------------------------------------------------
[sources]

[[sources.entries]]
url = "https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz"
checksum = "sha256:57ff8e8fd0497355dfcae6db4b1daef82ad6e3f23ec9e85795e80f8a4630b1dd"
format = "tar.xz"
priority = 1

[[sources.entries]]
url = "https://mirror.kernel.org/gnu/binutils/binutils-2.43.1.tar.xz"
format = "tar.xz"
priority = 2

# ------------------------------------------------------------
# Ambiente
# ------------------------------------------------------------
[environment]
CFLAGS = "-O2 -pipe -fPIC"
CXXFLAGS = "-O2 -pipe -fPIC"
LDFLAGS = "-Wl,-O1"
MAKEFLAGS = "-j$(nproc)"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"

# ------------------------------------------------------------
# Dependências
# ------------------------------------------------------------
[dependencies]
build = ["gcc", "make", "bash", "texinfo"]
runtime = ["glibc", "zlib"]
optional = ["gdb"]

# ------------------------------------------------------------
# Patches opcionais (se aplicáveis)
# ------------------------------------------------------------
[patches]
files = []

# ------------------------------------------------------------
# Hooks (pré/pós estágios)
# ------------------------------------------------------------
[hooks]
pre_configure = ""
post_configure = ""
pre_build = ""
post_build = ""
pre_install = ""
post_install = "scripts/update-info-dir.sh"
pre_remove = ""
post_remove = ""

# ------------------------------------------------------------
# Construção real
# ------------------------------------------------------------
[build]
system = "custom"
fakeroot = true
chroot = true
strip_binaries = true
commands = [
    "mkdir -pv build",
    "cd build",
    "../configure --prefix=/usr            \\
                  --enable-gold            \\
                  --enable-ld=default      \\
                  --enable-plugins         \\
                  --enable-shared          \\
                  --disable-werror         \\
                  --enable-64-bit-bfd      \\
                  --enable-lto             \\
                  --with-system-zlib",
    "make tooldir=/usr",
    "make check || true",
    "make install tooldir=/usr",
    "rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a"
]

# ------------------------------------------------------------
# Pós-instalação
# ------------------------------------------------------------
[post_install]
register = true
update_cache = true
clean_build_dir = true
notify = true

# ------------------------------------------------------------
# Empacotamento binário
# ------------------------------------------------------------
[package_build]
enabled = true
type = "tar"
output_dir = "/var/zeropkg/packages"
compress = "xz"
include_docs = true

# ------------------------------------------------------------
# Segurança e integridade
# ------------------------------------------------------------
[security]
verify_checksums = true
use_chroot = true
fakeroot = true
signature_check = false

# ------------------------------------------------------------
# Configuração LFS
# ------------------------------------------------------------
[lfs]
stage = "final"
toolchain = false
bootstrap = false
chroot_required = true
