# GNU Binutils — Pass 1 (LFS Toolchain)
# Receita real para uso com Zeropkg
# ------------------------------------------------------------
# Esta fase constrói os utilitários binutils no ambiente toolchain,
# dentro de /mnt/lfs/tools (isolado, sem headers ou libs do sistema host).
# ------------------------------------------------------------

[package]
name = "binutils"
version = "2.43.1"
category = "lfs"
variant = "pass1"
description = "GNU Binutils (fase 1) — montador e ligador para o toolchain inicial do LFS."
maintainer = "Zeropkg Build System"
license = "GPL-3.0"
homepage = "https://www.gnu.org/software/binutils/"

# ------------------------------------------------------------
# Fontes — download principal e mirrors
# ------------------------------------------------------------
[sources]

[[sources.entries]]
url = "https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz"
checksum = "sha256:57ff8e8fd0497355dfcae6db4b1daef82ad6e3f23ec9e85795e80f8a4630b1dd"
format = "tar.xz"
priority = 1

[[sources.entries]]
url = "https://mirror.kernel.org/gnu/binutils/binutils-2.43.1.tar.xz"
format = "tar.xz"
priority = 2

# ------------------------------------------------------------
# Ambiente — conforme manual do LFS
# ------------------------------------------------------------
[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/mnt/lfs/tools/bin:/usr/bin"
CONFIG_SITE = "/mnt/lfs/usr/share/config.site"

# ------------------------------------------------------------
# Dependências — somente GCC e glibc quando disponíveis
# ------------------------------------------------------------
[dependencies]
build = []
runtime = []

# ------------------------------------------------------------
# Construção — passos reais do LFS
# ------------------------------------------------------------
[build]
system = "custom"
fakeroot = false
chroot = false
strip_binaries = false
commands = [
    "mkdir -pv build",
    "cd build",
    "../configure --prefix=/mnt/lfs/tools --with-sysroot=$LFS --target=$LFS_TGT --disable-nls --enable-gprofng=no --disable-werror",
    "make",
    "make install"
]

# ------------------------------------------------------------
# Pós-instalação — limpeza e registro
# ------------------------------------------------------------
[post_install]
register = true
clean_build_dir = true
update_cache = true

# ------------------------------------------------------------
# Configuração específica para LFS
# ------------------------------------------------------------
[lfs]
stage = "toolchain"
toolchain = true
bootstrap = true
chroot_required = false

# ------------------------------------------------------------
# Hooks (opcionais)
# ------------------------------------------------------------
[hooks]
pre_configure = ""
post_install = ""
pre_remove = ""
post_remove = ""

# ------------------------------------------------------------
# Segurança e empacotamento
# ------------------------------------------------------------
[security]
verify_checksums = true
use_chroot = false
fakeroot = false

[package_build]
enabled = true
type = "tar"
output_dir = "/var/zeropkg/packages"
compress = "xz"
include_docs = false
