[package]
name = "binutils"
version = "2.43.1"
description = "GNU Binutils - Conjunto de ferramentas para manipular arquivos binários e objetos"
category = "development"
license = "GPLv3"
homepage = "https://www.gnu.org/software/binutils/"
maintainer = "Zeropkg LFS Automation"
stage = "final"
priority = "critical"

[source]
urls = [
  "https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz"
]
sha256 = [
  "0a9d4f9ed53d5cdb7d9a7c3eb2ad04dbb6f0b0c8a01a3c0b637d2a5b4e870ae4"
]
extract_to = "binutils-2.43.1"

[build]
depends = ["glibc", "zlib"]
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "build"

[environment]
PATH = "/usr/bin:/bin"
LC_ALL = "POSIX"
MAKEFLAGS = "-j$(nproc)"
CC = "gcc"
CXX = "g++"
CFLAGS = "-O2 -pipe"
CXXFLAGS = "-O2 -pipe"
LDFLAGS = "-Wl,-O1,--as-needed"

[prepare]
commands = [
  "mkdir -v build"
]

[configure]
commands = [
  "cd build",
  "../configure",
  "--prefix=/usr",
  "--enable-gold",
  "--enable-ld=default",
  "--enable-plugins",
  "--enable-shared",
  "--disable-werror",
  "--enable-64-bit-bfd",
  "--with-system-zlib"
]

[compile]
commands = [
  "cd build",
  "make -j$(nproc) tooldir=/usr"
]

[check]
enabled = true
commands = [
  "cd build",
  "make -k check || true"
]

[install]
commands = [
  "cd build",
  "make tooldir=/usr install"
]

[post_install_cleanup]
commands = [
  "rm -fv /usr/lib/libbfd.a /usr/lib/libopcodes.a"
]

[patches]
apply = []
strip = 1

[hooks]
pre_configure = [
  "echo '[HOOK] Preparando Binutils final para compilação...'"
]
post_install = [
  "echo '[HOOK] Binutils 2.43.1 instalado com sucesso em /usr/bin'"
]
post_remove = [
  "echo '[HOOK] Binutils removido. Recompile o toolchain se necessário.'"
]

[tests]
enabled = true
commands = [
  "cd build",
  "expect -c 'spawn make -k check; expect eof' || true",
  "grep '^FAIL' build/test-suite.log || true"
]

[package.files]
bin = ["/usr/bin/as", "/usr/bin/ld", "/usr/bin/nm", "/usr/bin/objdump"]
lib = ["/usr/lib/bfd*", "/usr/lib/libopcodes*"]
doc = ["/usr/share/doc/binutils-2.43.1"]

[package.meta]
provides = ["as", "ld", "nm", "objdump", "ar", "strip"]
conflicts = ["binutils-pass1"]
group = "toolchain"
keywords = ["linker", "assembler", "toolchain", "bfd"]

[install]
root = "/"
keep_build = false
safe_chroot = true
parallel_install = true
overwrite_existing = true

[notifications]
notify = true
urgency = "critical"
summary = "Binutils (Final) instalado com sucesso"
icon = "/usr/share/icons/binutils.png"
