[package]
name = "binutils"
version = "2.41"
category = "base"
description = "GNU Binutils - ferramentas de linkagem, montagem e manipulação de binários"
homepage = "https://www.gnu.org/software/binutils/"
licenses = ["GPL-3.0-or-later"]

[dependencies]
build = ["gcc", "make", "texinfo"]
runtime = []

[source]
urls = [
    "https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz",
    "https://ftpmirror.gnu.org/binutils/binutils-2.41.tar.xz"
]
sha256 = "5b9c09b2fffb2c9b03a07e0ed0b8e8ab9d40f83dbb2519038b7a769ffed3cf1a"

[patches]
files = []

[build]
# usamos diretório separado de build
configure = "../configure \
    --prefix=/usr \
    --enable-gold \
    --enable-ld=default \
    --enable-plugins \
    --enable-shared \
    --disable-werror \
    --enable-64-bit-bfd"
make = "make -j$(nproc)"
check = "make -k check"
install = "make install"

[build.env]
PATH = "/usr/bin:/bin"
CONFIG_SITE = "none"

[hooks]
pre_configure = "echo '[HOOK] Preparando build do binutils...'"
post_install = "rm -f /usr/lib/lib{bfd,opcodes}.a; echo '[HOOK] Binutils instalado com sucesso'"

[options]
fakeroot = true
chroot = true
package_before_install = true
run_tests = true

[files]
bin = [
    "/usr/bin/addr2line",
    "/usr/bin/ar",
    "/usr/bin/as",
    "/usr/bin/ld",
    "/usr/bin/nm",
    "/usr/bin/objcopy",
    "/usr/bin/objdump",
    "/usr/bin/ranlib",
    "/usr/bin/readelf",
    "/usr/bin/size",
    "/usr/bin/strings",
    "/usr/bin/strip"
]
lib = ["/usr/lib/*bfd*", "/usr/lib/*opcodes*"]
doc = ["/usr/share/info/binutils.info"]
