[package]
name = "binutils"
version = "2.43.1"
stage = "pass1"
description = "Binutils - ferramentas essenciais de linkagem e montagem (fase 1 do toolchain)"
category = "toolchain"
license = "GPLv3"
maintainer = "Zeropkg LFS Automation"
homepage = "https://www.gnu.org/software/binutils/"
priority = "critical"

[source]
urls = ["https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz"]
sha256 = ["0a9d4f9ed53d5cdb7d9a7c3eb2ad04dbb6f0b0c8a01a3c0b637d2a5b4e870ae4"]
extract_to = "binutils-2.43.1"

[build]
depends = []
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "build"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/usr/bin:/bin"
MAKEFLAGS = "-j$(nproc)"
LC_ALL = "POSIX"
CC = "gcc"
CXX = "g++"
CFLAGS = "-O2 -pipe"
CXXFLAGS = "-O2 -pipe"

[prepare]
commands = [
  "mkdir -pv build"
]

[configure]
commands = [
  "cd build",
  "../configure",
  "--prefix=$LFS/tools",
  "--with-sysroot=$LFS",
  "--target=$LFS_TGT",
  "--disable-nls",
  "--enable-gprofng=no",
  "--disable-werror"
]

[compile]
commands = [
  "cd build",
  "make -j$(nproc)"
]

[install]
commands = [
  "cd build",
  "make install"
]

[hooks]
pre_configure = [
  "echo '[HOOK] Iniciando build do Binutils (Pass 1)'"
]
post_install = [
  "echo '[HOOK] Binutils Pass 1 instalado em $LFS/tools/bin'"
]

[patches]
apply = []
strip = 1

[tests]
enabled = false

[package.meta]
provides = ["as", "ld", "nm", "objdump", "ar", "strip"]
group = "toolchain"
conflicts = []
replaces = []

[install]
root = "/mnt/lfs"
keep_build = false
safe_chroot = true
parallel_install = false
overwrite_existing = true

[package.files]
bin = ["/mnt/lfs/tools/bin/as", "/mnt/lfs/tools/bin/ld"]
lib = ["/mnt/lfs/tools/lib/bfd", "/mnt/lfs/tools/lib/opcodes"]

[notifications]
notify = true
urgency = "critical"
summary = "Binutils (Pass 1) instalado com sucesso em $LFS/tools"
icon = "/usr/share/icons/binutils.png"
