[paths]
db_path = "/var/lib/zeropkg/installed.sqlite3"
ports_dir = "/usr/ports"
build_root = "/var/zeropkg/build"
cache_dir = "/usr/ports/distfiles"
packages_dir = "/var/zeropkg/packages"

[options]
jobs = 4
fakeroot = true
chroot_enabled = true
auto_clean = true
log_level = "INFO"

[repos]
# Repositório principal oficial
main = "https://github.com/fcanata00/Zeropkg-Ports.git"

# Repositório experimental (opcional)
testing = "https://github.com/fcanata00/Zeropkg-Testing.git"

# Mirror local (opcional)
local = "/mnt/repos/zeropkg-local"

[network]
proxy = ""
verify_ssl = true
retries = 3
timeout = 30

[lfs]
# Caminho base para construir o Linux From Scratch
root = "/mnt/lfs"
chroot_shell = "/bin/bash"
user = "lfs"
group = "lfs"
