[package]
name = "examplepkg"
version = "1.0"
category = "devel"
description = "Exemplo de pacote com múltiplas fontes, incluindo Git"
homepage = "https://example.org"
licenses = ["GPL-3.0-or-later"]
maintainer = "Você <voce@example.org>"

[dependencies]
runtime = ["zlib", "openssl"]
build = ["make", "pkg-config"]

[source]
# múltiplas opções: tarball + git
urls = [
    "https://example.org/releases/examplepkg-1.0.tar.gz",
    "https://mirror.example.net/examplepkg/examplepkg-1.0.tar.gz",
    "git+https://github.com/example/examplepkg.git"
]
# hash só usado para tarballs
sha256 = "SOME_SHA256_HASH"
# branch/tag/commit se usar git
git_branch = "main"
git_commit = "abcdef1234567890"

[patches]
files = [
    "examplepkg-fix-config.patch",
    "examplepkg-security.patch"
]

[build]
configure = "./configure --prefix=/usr --enable-feature-x --disable-nls"
make = "make -j$(nproc)"
check = "make check"
install = "make install DESTDIR=${PKGDIR}"

[build.env]
CFLAGS = "-O2 -pipe -march=native"
LDFLAGS = "-Wl,-O1,--as-needed"
PKG_CONFIG_PATH = "/usr/lib/pkgconfig:/usr/share/pkgconfig"
SOMEFLAG = "enabled"

[hooks]
pre_configure = "echo '[HOOK] Rodando pre-configure...'"
post_configure = "echo '[HOOK] Configuração finalizada!'"
pre_install = "echo '[HOOK] Instalando em fakeroot...'"
post_install = "strip --strip-unneeded ${PKGDIR}/usr/bin/* || true"
pre_remove = "echo '[HOOK] Removendo examplepkg...'"
post_remove = "echo '[HOOK] examplepkg removido com sucesso!'"

[options]
fakeroot = true
chroot = true
package_before_install = true
run_tests = true

[files]
bin = ["/usr/bin/example"]
lib = ["/usr/lib/libexample.so*"]
doc = ["/usr/share/doc/examplepkg/*"]
