[package]
name = "coreutils"
version = "9.3"
category = "lfs"
description = "GNU Coreutils — utilitários básicos de sistema (LFS Chapter 6.5)"
homepage = "https://www.gnu.org/software/coreutils/"
license = "GPL-3.0-or-later"
maintainer = "zeropkg"

[sources]
urls = [
  "https://ftp.gnu.org/gnu/coreutils/coreutils-9.3.tar.xz"
]
checksum = "sha256:<COLOQUE_SHA256_REAL_DO_COREUTILS_9.3>"
extract_to = "coreutils-9.3"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/mnt/lfs/tools/bin:/usr/bin:/bin"
DESTDIR = "@DESTDIR@"

[build]
chroot = true
fakeroot = false
cleanup_sources = true
commands = [
  "./configure --prefix=/usr \\",
  "  --host=$LFS_TGT \\",
  "  --build=$(build-aux/config.guess) \\",
  "  --enable-install-program=hostname \\",
  "make",
  "make DESTDIR=${DESTDIR} install"
]

[hooks]
pre_build = "echo '==> Construindo Coreutils 9.3 (LFS temporário)'"
post_install = "echo '==> Coreutils instalados com sucesso'"

[dependencies]
build = ["bash-5.2.37"]
runtime = []

[lfs]
stage = "toolchain"
bootstrap = true
chroot_required = true
