# /usr/ports/coreutils/coreutils-9.6.toml
[package]
name = "coreutils"
version = "9.6"
description = "GNU Core Utilities - utilitários básicos do sistema"
category = "tools"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/coreutils/"
maintainer = "Zeropkg LFS Automation"
stage = "toolchain"
priority = "normal"

[source]
urls = ["https://ftp.gnu.org/gnu/coreutils/coreutils-9.6.tar.xz"]
# SHA256 obtido do anúncio oficial/FTP do GNU.
sha256 = ["7a0124327b398fd9eb1a6abde583389821422c744ffa10734b24f557610d3283"]
extract_to = "coreutils-9.6"

[build]
# Coreutils no LFS capítulo 6 é construído in-tree (sem build/ separado).
depends = []
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "coreutils-9.6"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/tools/bin:/usr/bin:/bin"
MAKEFLAGS = "-j$(nproc)"
LC_ALL = "POSIX"
CFLAGS = "-O2 -pipe"

# prepare: (não precisa criar "build" - coreutils usa build in-tree)
prepare = [
  "echo '[prepare] Source ready: $(pwd)'"
]

# configure: usar exatamente as opções LFS (hostname habilitado; kill/uptime desabilitados)
configure = [
  "pushd .",
  "./configure --prefix=/usr --host=$LFS_TGT --build=$(build-aux/config.guess) \\",
  "  --enable-install-program=hostname \\",
  "  --enable-no-install-program=kill,uptime",
  "popd"
]

compile = [
  "make"
]

# instalar para DESTDIR=$LFS conforme LFS
install = [
  "make DESTDIR=$LFS install"
]

# comandos pós-instalação: mover chroot para /usr/sbin e ajustar manpage para man8
# (essas ações são necessárias mesmo no ambiente temporário do LFS).
post_install = [
  "mv -v $LFS/usr/bin/chroot $LFS/usr/sbin || true",
  "mkdir -pv $LFS/usr/share/man/man8",
  "mv -v $LFS/usr/share/man/man1/chroot.1 $LFS/usr/share/man/man8/chroot.8 || true",
  "sed -i 's/\"1\"/\"8\"/' $LFS/usr/share/man/man8/chroot.8 || true"
]

[hooks]
pre_configure = ["echo '[HOOK] iniciando configure coreutils'"]
post_install_hook = ["echo '[HOOK] coreutils instalado e movido (chroot->/usr/sbin)'" ]

[patches]
apply = []
strip = 1

[tests]
# LFS não exige 'make check' aqui — mantemos testes desabilitados por padrão.
enabled = false
commands = []

[package.files]
bin = [
  "/usr/bin/ls", "/usr/bin/cp", "/usr/bin/mv", "/usr/bin/rm",
  "/usr/bin/mkdir", "/usr/bin/ln", "/usr/bin/chmod", "/usr/bin/chown"
]
sbin = ["/usr/sbin/chroot"]
man = ["/usr/share/man/man1/*", "/usr/share/man/man8/*"]

[package.meta]
provides = ["coreutils"]
group = "base"
keywords = ["core", "utils"]

[install]
# por padrão instala em / quando chamado sem --root; para LFS use --root /mnt/lfs
root = "/"
keep_build = false
safe_chroot = true
parallel_install = true
overwrite_existing = true

[notifications]
notify = true
urgency = "normal"
summary = "Coreutils 9.6 instalado"
