[package]
name = "linux-api-headers"
version = "6.6.32"
description = "Linux API Headers - Cabeçalhos da API do kernel usados pela glibc"
category = "system"
license = "GPLv2"
homepage = "https://www.kernel.org"
maintainer = "Zeropkg LFS Automation"
stage = "final"
priority = "critical"

[source]
urls = [
  "https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.6.32.tar.xz"
]
sha256 = [
  "efaa2b4f3a6e2479e8a8b0b95f5f7cfde2357b3a0de8b7da134f01f94acfc9b0"
]
extract_to = "linux-6.6.32"

[build]
depends = []
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "linux-6.6.32"

[environment]
PATH = "/usr/bin:/bin"
LC_ALL = "POSIX"
MAKEFLAGS = "-j$(nproc)"
CFLAGS = "-O2 -pipe"
CXXFLAGS = "-O2 -pipe"

[prepare]
commands = [
  "make mrproper"
]

[compile]
commands = [
  "make headers"
]

[install]
commands = [
  "find usr/include -type f ! -name '*.h' -delete",
  "cp -rv usr/include /usr"
]

[hooks]
pre_build = [
  "echo '[HOOK] Iniciando build do Linux API Headers 6.6.32...'"
]
post_install = [
  "echo '[HOOK] Headers copiados para /usr/include'"
]

[patches]
apply = []
strip = 1

[tests]
enabled = false

[package.files]
include = ["/usr/include/linux", "/usr/include/asm"]
doc = ["/usr/share/doc/linux-api-headers-6.6.32"]

[package.meta]
provides = ["linux-api-headers"]
group = "toolchain"
conflicts = []
replaces = []

[install]
root = "/"
keep_build = false
safe_chroot = true
parallel_install = false
overwrite_existing = true

[notifications]
notify = true
urgency = "normal"
summary = "Linux API Headers 6.6.32 instalados em /usr/include"
icon = "/usr/share/icons/kernel.png"
