[package]
name = "gcc"
version = "13.2.0"
category = "base"
description = "GNU Compiler Collection - compilador completo C e C++"
homepage = "https://gcc.gnu.org/"
licenses = ["GPL-3.0-or-later"]

[dependencies]
build = ["binutils", "gmp", "mpfr", "mpc", "isl", "zlib"]
runtime = ["glibc"]

[source]
urls = [
    "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz"
]
sha256 = "e1cf5a63d89c9f9d3ff3efc4f8c7e2e61d4e2f6b41f6a54e7a57c3d89bfbf2f2"

extra = [
    { name = "mpfr", url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.xz", sha256 = "a5d1..." },
    { name = "gmp", url = "https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz", sha256 = "fd482..." },
    { name = "mpc", url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz", sha256 = "17503..." },
    { name = "isl", url = "https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.26.tar.xz", sha256 = "..." }
]

[patches]
files = []

[build]
configure = "../configure \
    --prefix=/usr \
    --enable-languages=c,c++ \
    --disable-multilib \
    --disable-bootstrap \
    --with-system-zlib"
make = "make -j$(nproc)"
check = "make -k check"
install = "make install"

[build.env]
PATH = "/usr/bin:/bin"
CONFIG_SITE = "none"

[hooks]
pre_configure = "echo '[HOOK] Preparando build do gcc final...'"
post_install = "ln -sv gcc /usr/bin/cc || true; echo '[HOOK] GCC instalado com sucesso'"

[options]
fakeroot = true
chroot = true
package_before_install = true
run_tests = true

[files]
bin = [
    "/usr/bin/gcc",
    "/usr/bin/c++",
    "/usr/bin/cc"
]
lib = [
    "/usr/lib/gcc/*"
]
doc = [
    "/usr/share/info/gcc.info",
    "/usr/share/man/man1/gcc.1"
]
