[package]
name = "gcc"
version = "13.2.0-pass1"
category = "toolchain"
description = "GNU Compiler Collection (primeira passagem) para LFS toolchain"
homepage = "https://gcc.gnu.org/"
licenses = ["GPL-3.0-or-later"]

[dependencies]
build = ["binutils-pass1", "gmp", "mpfr", "mpc"]
runtime = []

[source]
urls = [
    "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz"
]
sha256 = "e1cf5a63d89c9f9d3ff3efc4f8c7e2e61d4e2f6b41f6a54e7a57c3d89bfbf2f2"

# subcomponentes necessários
extra = [
    { name = "mpfr", url = "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.xz", sha256 = "a5d1..." },
    { name = "gmp", url = "https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz", sha256 = "fd482..." },
    { name = "mpc", url = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz", sha256 = "17503..." }
]

[patches]
files = []

[build]
# usamos diretório separado para build
configure = "../configure \
    --target=$LFS_TGT \
    --prefix=/tools \
    --with-glibc-version=2.39 \
    --with-sysroot=$LFS \
    --with-newlib \
    --without-headers \
    --enable-initfini-array \
    --disable-nls \
    --disable-shared \
    --disable-multilib \
    --disable-decimal-float \
    --disable-threads \
    --disable-libatomic \
    --disable-libgomp \
    --disable-libquadmath \
    --disable-libssp \
    --disable-libvtv \
    --disable-libstdcxx \
    --enable-languages=c,c++"
make = "make -j$(nproc)"
check = ""   # geralmente pulado no pass1
install = "make install"

[build.env]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/mnt/lfs/tools/bin:/usr/bin:/bin"
CONFIG_SITE = "none"

[hooks]
pre_configure = "echo '[HOOK] Preparando build do gcc-pass1...'"
post_install = "ln -sv gcc /mnt/lfs/tools/bin/cc || true"

[options]
fakeroot = true
chroot = false
package_before_install = true
run_tests = false

[files]
bin = ["/tools/bin/gcc", "/tools/bin/cc"]
lib = ["/tools/lib/gcc/*"]
doc = []
