[package]
name = "gcc"
version = "13.2.0-pass1"
description = "GNU Compiler Collection (Pass 1) – parte do toolchain temporário do LFS"

[source]
urls = [
  "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz",
  "https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.xz",
  "https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz",
  "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz"
]
sha256 = [
  "e1761b92bd6ecb1d02d0cc39df1c47cb57b8cf6df569da91b6a4f1ad5f8f3b91",
  "13dfdec0c7b8e6e9d1a95f9a7a79d607b098dcc8e0bb4cfdc1c7f8b3b50b1f3e",
  "fd4829912cddd12f53fa4a5e4a8b0c2b8e6b0bfb47a1f23a68d2cb49e504bb2b",
  "a685a66e3d8c5b76e05b6b6fdcfaedec6c531da1b1c8f04f7af0b7d32fb4a42f"
]
extract_to = "gcc-13.2.0"

[build]
depends = ["binutils-pass1", "linux-headers"]
workdir = "build"
use_chroot = true
fakeroot = true

# Scripts de preparação e configuração
prepare = [
  "tar -xf ../mpfr-4.2.0.tar.xz",
  "mv -v mpfr-4.2.0 mpfr",
  "tar -xf ../gmp-6.2.1.tar.xz",
  "mv -v gmp-6.2.1 gmp",
  "tar -xf ../mpc-1.3.1.tar.gz",
  "mv -v mpc-1.3.1 mpc",
  "case $(uname -m) in",
  "  x86_64) sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64 ;;",
  "esac",
  "mkdir -v build"
]

configure = [
  "cd build",
  "../configure",
  "--target=$LFS_TGT",
  "--prefix=/tools",
  "--with-glibc-version=2.39",
  "--with-sysroot=$LFS",
  "--with-newlib",
  "--without-headers",
  "--enable-initfini-array",
  "--disable-nls",
  "--disable-shared",
  "--disable-multilib",
  "--disable-decimal-float",
  "--disable-threads",
  "--disable-libatomic",
  "--disable-libgomp",
  "--disable-libquadmath",
  "--disable-libssp",
  "--disable-libvtv",
  "--disable-libstdcxx",
  "--enable-languages=c,c++"
]

compile = [
  "cd build",
  "make -j$(nproc)"
]

install = [
  "cd build",
  "make install"
]

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/tools/bin:/usr/bin:/bin"
CONFIG_SITE = "/usr/share/config.site"

[hooks]
pre_configure = [
  "echo '[GCC PASS1] Preparando ambiente...'"
]
post_install = [
  "echo '[GCC PASS1] Instalação concluída em /mnt/lfs/tools'"
]

[package.meta]
category = "toolchain"
stage = "pass1"
maintainer = "Zeropkg LFS Automation"
license = "GPLv3"
homepage = "https://gcc.gnu.org/"
