[package]
name = "libstdcxx"
version = "13.2.0"
stage = "after-gcc-pass1"
description = "GNU Standard C++ Library (parte do GCC)"
category = "toolchain"
license = "GPLv3"
homepage = "https://gcc.gnu.org"
maintainer = "Zeropkg LFS Automation"
priority = "critical"

[source]
# Usa o mesmo tarball do GCC — o módulo downloader já terá o GCC baixado
urls = ["https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz"]
sha256 = ["PLACEHOLDER_SHA256_GCC_13_2_0"]
extract_to = "gcc-13.2.0"

[build]
depends = ["glibc", "gcc"]  # o GCC já construído no pass1
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "build-libstdcxx"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/tools/bin:/usr/bin:/bin"
MAKEFLAGS = "-j$(nproc)"
CXXFLAGS = "-O2 -pipe"
CFLAGS = "-O2 -pipe"
LANG = "en_US.UTF-8"

[prepare]
commands = [
  "mkdir -v build-libstdcxx"
]

[configure]
commands = [
  "cd build-libstdcxx",
  "../libstdc++-v3/configure",
  "--host=$LFS_TGT",
  "--build=$(../config.guess)",
  "--prefix=/usr",
  "--disable-multilib",
  "--disable-nls",
  "--disable-libstdcxx-pch",
  "--with-gxx-include-dir=/tools/$LFS_TGT/include/c++/13.2.0"
]

[compile]
commands = ["make"]

[install]
commands = ["make DESTDIR=$LFS install"]

[hooks]
post_install = [
  "rm -v $LFS/usr/lib/libstdc++{,fs,exp}.la",
  "rm -v $LFS/usr/lib/supc++.la"
]

[patches]
apply = []
strip = 1

[tests]
enabled = false

[package.files]
lib = ["/usr/lib/libstdc++.so.6"]
conf = []
doc = ["/usr/share/doc/libstdc++-13.2.0"]

[package.meta]
provides = ["stdc++"]
conflicts = []
replaces = []

[install]
root = "/mnt/lfs"
safe_chroot = true
parallel_install = false
keep_build = false
overwrite_existing = true

[notifications]
notify = true
urgency = "normal"
summary = "libstdc++ compilada e instalada"
icon = "/usr/share/icons/libstdcxx.png"
