[package]
name = "m4"
version = "1.4.20"
description = "GNU M4 macro processor"
category = "tools"
license = "GPLv3"
homepage = "https://www.gnu.org/software/m4/"
maintainer = "Zeropkg LFS Automation"
stage = "toolchain"
priority = "normal"

[source]
urls = [
  "https://ftp.gnu.org/gnu/m4/m4-1.4.20.tar.xz"
]
sha256 = [
  "c0e9bfefb51f6ea61e7c1a221a3f9cd16e169e4cbfa3e0cb8dcf4dc7ab1cd7e9"
]
extract_to = "m4-1.4.20"

[build]
depends = []
optional_depends = []
use_chroot = true
fakeroot = true
workdir = "build"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
MAKEFLAGS = "-j$(nproc)"
PATH = "/tools/bin:/usr/bin:/bin"
CFLAGS = "-O2 -pipe"
LC_ALL = "POSIX"

[configure]
commands = [
  "./configure --prefix=/usr --host=$LFS_TGT --build=$(./build-aux/config.guess)"
]

[compile]
commands = ["make"]

[install]
commands = ["make DESTDIR=$LFS install"]

[hooks]
pre_configure = ["echo '[HOOK] Preparando M4 1.4.20...'"]
post_install = ["echo '[HOOK] M4 instalado em /usr no chroot'"]

[patches]
apply = []
strip = 1

[tests]
enabled = false

[package.files]
bin = ["/usr/bin/m4"]
doc = ["/usr/share/doc/m4-1.4.20"]

[package.meta]
provides = ["m4"]
group = "tools"
conflicts = []
replaces = []

[install]
root = "/mnt/lfs"
safe_chroot = true
parallel_install = false
keep_build = false
overwrite_existing = true

[notifications]
notify = true
urgency = "normal"
summary = "M4 1.4.20 instalado"
icon = "/usr/share/icons/m4.png"
