[package]
name = "glibc"
version = "2.42"
stage = "pass1"
description = "GNU C Library - Fase 1 do Toolchain"
category = "toolchain"
license = "LGPLv2.1+"
homepage = "https://www.gnu.org/software/libc/"
maintainer = "Zeropkg LFS Automation"
priority = "critical"

[source]
urls = ["https://ftp.gnu.org/gnu/glibc/glibc-2.42.tar.xz"]
sha256 = ["PLACEHOLDER_SHA256"]
extract_to = "glibc-2.42"

[build]
depends = ["linux-api-headers"]
use_chroot = true
fakeroot = true
workdir = "build"

[environment]
LFS = "/mnt/lfs"
LFS_TGT = "x86_64-lfs-linux-gnu"
PATH = "/tools/bin:/usr/bin:/bin"
MAKEFLAGS = "-j$(nproc)"
CFLAGS = "-O2 -pipe"
CXXFLAGS = "-O2 -pipe"
LANG = "en_US.UTF-8"

[prepare]
commands = [
  "case $(uname -m) in",
  "  i?86) ln -sfv ld-linux.so.2 $LFS/lib/ld-lsb.so.3 ;;",
  "  x86_64) ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64 &&",
  "           ln -sfv ../lib/ld-linux-x86-64.so.2 $LFS/lib64/ld-lsb-x86-64.so.3 ;;",
  "esac",
  "patch -Np1 -i ../glibc-2.42-fhs-1.patch",
  "echo \"rootsbindir=/usr/sbin\" > configparms",
  "mkdir -v build"
]

[configure]
commands = [
  "cd build",
  "../configure",
  "--prefix=/usr",
  "--host=$LFS_TGT",
  "--build=$(../scripts/config.guess)",
  "--enable-kernel=5.4",
  "--with-headers=$LFS/usr/include",
  "libc_cv_slibdir=/usr/lib"
]

[compile]
commands = ["make"]

[install]
commands = ["make DESTDIR=$LFS install"]

[tests]
enabled = true
commands = [
  "echo 'int main(){}' > dummy.c",
  "$LFS_TGT-gcc dummy.c -o dummy",
  "readelf -l dummy | grep ld-linux",
  "grep -E -o '$LFS/lib.*/S?crt[1in].*succeeded' dummy.log || true",
  "rm -v dummy.c dummy dummy.log"
]

[hooks]
post_install = [
  "sed '/RTLDLIST=/s@/usr@@g' -i $LFS/usr/bin/ldd",
  "echo '[HOOK] Glibc Pass1 instalado com sucesso em $LFS/usr'"
]

[package.files]
lib = ["/usr/lib/libc.so.6"]
doc = ["/usr/share/doc/glibc-2.42"]

[package.meta]
provides = ["glibc-pass1"]
group = "toolchain"

[install]
root = "/mnt/lfs"
safe_chroot = true
parallel_install = false
keep_build = false
overwrite_existing = true
